FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/streamlit_app/ src/streamlit_app/

EXPOSE 8501
CMD ["streamlit", "run", "src/streamlit_app/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
